{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "starter-kit-chart.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  to:
    kind: Service
    name: {{ include "starter-kit-chart.fullname" . }}
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}